import pandas as pd

# branch_df = pd.read_csv('database/branch.csv', sep=',', header=0)
departments_df = pd.read_csv('database/departments.csv', sep=',', header=0)
# staff_df = pd.read_csv('database/staff.csv', sep=',', header=0)
# customers_df = pd.read_csv('database/customers.csv', sep=',', header=0)
# customer_contacts_df = pd.read_csv('database/customer_contacts.csv', sep=',', header=0)
# providers_df = pd.read_csv('database/providers.csv', sep=',', header=0)
# provider_contacts_df = pd.read_csv('database/provider_contacts.csv', sep=',', header=0)
# products_df = pd.read_csv('database/products.csv', sep=',', header=0)
# labeling_df = pd.read_csv('database/labeling.csv', sep=',', header=0)
# packaging_df = pd.read_csv('database/packaging.csv', sep=',', header=0)
# assortment_df = pd.read_csv('database/assortment.csv', sep=',', header=0)
# shipment_from_china_df = pd.read_csv('database/shipment_from_china.csv', sep=',', header=0)
# warehouses_df = pd.read_csv('database/warehouses.csv', sep=',', header=0)
# transport_df = pd.read_csv('database/transport.csv', sep=',', header=0)
# delivery_to_customers_df = pd.read_csv('database/delivery_to_customers.csv', sep=',', header=0)
# moving_around_warehouses_df = pd.read_csv('database/moving_around_warehouses.csv', sep=',', header=0) 

# branch_df = branch_df.drop('main_id', axis=1)
# assortment_df = assortment_df.rename(columns={'name_rus':'description'})
# customer_contacts_df.insert(5,'email', ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], False)
# branch_df[['zip', 'street', 'building']] = ''
# shipment_from_china_df.to_csv('database/shipment_from_china.csv', index=False)
# print(len(max(shipment_df.gtd, key=len)))
# print(assortment_df.columns.to_list())

# print(branch_df)
print(departments_df)
# print(staff_df)
# print(customers_df)
# print(customer_contacts_df)
# print(providers_df)
# print(provider_contacts_df)
# print(products_df)
# print(labeling_df)
# print(packaging_df)
# print(assortment_df)
# print(shipment_from_china_df)
# print(warehouses_df)
# print(transport_df)
# print(delivery_to_customers_df)
# print(moving_around_warehouses_df)