import pandas as pd

main_df = pd.read_csv('database/main.csv', sep=',', header=0)
branch_df = pd.read_csv('database/branch.csv', sep=';', header=0)
departments_df = pd.read_csv('database/departments.csv', sep=';', header=0)
staff_df = pd.read_csv('database/staff.csv', sep=';', header=0)
customers_df = pd.read_csv('database/customers.csv', sep=',', header=0)
customer_contacts_df = pd.read_csv('database/customer_contacts.csv', sep=',', header=0) 
providers_df = pd.read_csv('database/providers.csv', sep=';', header=0)
provider_contacts_df = pd.read_csv('database/provider_contacts.csv', sep=',', header=0)
products_df = pd.read_csv('database/products.csv', sep=';', header=0)
assortment_df = pd.read_csv('database/assortment.csv', sep=';', header=0)
packaging_df = pd.read_csv('database/packaging.csv', sep=';', header=0)

# customer_contacts_df = customers_contacts_df.drop('main_id', axis=1)
# customer_contacts_df = customers_contacts_df.rename(columns={'contact_person':'f_name', 'contact_phone':'phone'})
# customer_contacts_df.insert(5,'email', ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], False)
# print(customers_df)
print(assortment_df)
# customer_contacts_df.to_csv('database/customer_contacts.csv', index=False)
# print(len(max(customers_df.customer_name, key=len)))